---
- name: Alterar senha do usuário root
  hosts: all
  become: true

  vars:
    nova_senha_root: "NovaSenhaSegura123"

  tasks:
    - name: Gerar hash da nova senha
      ansible.builtin.set_fact:
        senha_hash: "{{ nova_senha_root | password_hash('sha512') }}"

    - name: Alterar senha do root
      ansible.builtin.user:
        name: root
        password: "{{ senha_hash }}"
  ignore_errors: yes