---
- name: Configurar repositório local nos clientes RHEL 6
  hosts: clientes_rhel6
  become: yes
  vars:
    repo_url: http://10.10.10.10:8080/repos/rhel6

  tasks:
    - name: Apagar repositórios antigos
      file:
        path: /etc/yum.repos.d/
        state: absent
        recurse: yes

    - name: Recriar diretório de repositórios
      file:
        path: /etc/yum.repos.d/
        state: directory
        mode: '0755'

    - name: Criar repositório local
      copy:
        dest: /etc/yum.repos.d/local-rhel6.repo
        content: |
          [local-rhel6]
          name=Repositório Local RHEL6
          baseurl={{ repo_url }}
          enabled=1
          gpgcheck=0
        mode: '0644'
  ignore_errors: yes