---
- name: Reset user password securely
  hosts: all
  become: yes
  gather_facts: no

  vars:
    username: ""
    password: ""

  tasks:
    - name: Reset user password with random salt
      user:
        name: "{{ username }}"
        password: "{{ password | password_hash('sha512', salt=lookup('password', '/dev/null length=8 chars=ascii_letters')) }}"
        update_password: always
