[root@SPRDBDORAGRU12 ~]# cat /etc/multipath.conf
# device-mapper-multipath configuration file

# For a complete list of the default configuration values, run either:
# # multipath -t
# or
# # multipathd show config

# For a list of configuration options with descriptions, see the
# multipath.conf man page.

defaults {
        user_friendly_names yes
        find_multipaths yes
        enable_foreign "^$"
}

blacklist_exceptions {
        property "(SCSI_IDENT_|ID_WWN)"
}

blacklist {
}

multipaths {
        multipath {
                wwid “36000d3100061a200000000000000037f”
                alias “ORABKP01”
                }
        multipath {
                wwid “36000d3100061a2000000000000000371”
                alias “ORAECP01”
                }
        multipath {
                wwid “36000d3100061a2000000000000000372”
                alias “ORAECP02”
                }
        multipath {
                wwid “36000d3100061a2000000000000000373”
                alias “ORAECP03”
                }
         multipath {
                wwid “36000d3100061a2000000000000000374”
                alias “ORAECP04”
                }
         multipath {
                wwid “36000d3100061a2000000000000000375”
                alias “ORAECP05”
                }
         multipath {
                wwid “36000d3100061a200000000000000037b”
                alias “ORARECO01”
                }
         multipath {
                wwid “36000d3100061a200000000000000037c”
                alias “ORARECO02”
                }
         multipath {
                wwid “36000d3100061a200000000000000037d”
                alias “ORARECO03”
                }
         multipath {
                wwid “36000d3100061a200000000000000037e”
                alias “ORARECO04”
                }
         multipath {
                wwid “36000d3100061a2000000000000000379”
                alias “ORAREP01”
                }
        multipath {
                wwid “36000d3100061a200000000000000037a”
                alias “ORAREP02”
                }
        multipath {
                wwid “36000d3100061a2000000000000000376”
                alias “ORASOL01”
                }
         multipath {
                wwid “36000d3100061a2000000000000000377”
                alias “ORASOL02”
                }
        multipath {
                wwid “36000d3100061a2000000000000000378”
                alias “ORASOL03”
                }
        multipath {
                wwid “36000d3100061a2000000000000000380”
                alias “ORAU01”
                }
}

[root@SPRDBDORAGRU12 ~]#
